from dc3pa.experiments.development_records import DevelopmentDecisionRecord


def make_record(
    record_id,
    *,
    role="dev_train",
    confidence_level="medium",
    correct=True,
    compatibility=0.7,
    coverage=0.8,
    similarity=0.9,
    raw_state="matched",
    hard_feasible=True,
    knowledge_coverage=0.7,
    knowledge_unknown=False,
):
    return DevelopmentDecisionRecord(
        record_id=record_id,
        collection_id="collection",
        development_input_release_id="dev-input",
        development_protocol_id="protocol",
        role=role,
        group_id=f"group-{record_id}",
        task="craft wooden pressure plate",
        seed=str(abs(hash(record_id)) % 100000),
        difficulty="easy",
        run_id=f"run-{record_id}",
        decision_index=0,
        source_commit="a" * 40,
        paper_memory_v5_release_id="memory-v5",
        snapshot_root_sha256_before="snapshot-root",
        snapshot_root_sha256_after="snapshot-root",
        bootstrap_policy_id="bootstrap",
        prompt_hash_bundle_id="prompts",
        requested_model_name="gpt-5.1",
        returned_model_identities=("returned-id",),
        local_subgoal="craft pressure plate",
        proposed_action="craft wooden pressure plate",
        knowledge_hard_feasible=hard_feasible,
        knowledge_coverage=knowledge_coverage,
        knowledge_unknown=knowledge_unknown,
        knowledge_missing_prerequisites=(),
        confidence_level=confidence_level,
        environment_topk_exemplar_ids=("scene-1",),
        environment_topk_similarities=(similarity,),
        environment_compatibility=compatibility,
        environment_coverage=coverage,
        environment_raw_state=raw_state,
        decision_correct=correct,
        task_completed=correct,
        planner_calls=1,
        reflection_calls=0 if correct else 1,
        evaluation_chain_calls=0,
        controller_calls=1,
        bootstrap_event_count=1,
        injected_log_count=1,
        input_tokens=10,
        output_tokens=5,
        reasoning_tokens=1,
        latency_ms=100.0,
        formal_memory_write_count=0,
        acquisition_write_count=0,
        holdout_accessed=False,
        excluded_from_final_evaluation=True,
    ).with_hash()
